# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{space-saver-redis}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Aaron Windsor"]
  s.date = %q{2014-08-26}
  s.description = %q{A pure Ruby implementation of the SpaceSaver algorithm for approximating the top K elements in a data stream, backed by Redis}
  s.email = %q{aaron.windsor@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/space-saver-redis.rb",
    "space-saver-redis.gemspec",
    "spec/space-saver-redis_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/aaw/space-saver-redis}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{A pure Ruby implementation of the SpaceSaver algorithm for approximating the top K elements in a data stream, backed by Redis}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<redis>, [">= 3.0.1", "~> 3.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<rake>, ["~> 0.9.2.2"])
      s.add_development_dependency(%q<rspec>, ["~> 2.11.0"])
      s.add_development_dependency(%q<timecop>, ["~> 0.5.3"])
    else
      s.add_dependency(%q<redis>, [">= 3.0.1", "~> 3.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<rake>, ["~> 0.9.2.2"])
      s.add_dependency(%q<rspec>, ["~> 2.11.0"])
      s.add_dependency(%q<timecop>, ["~> 0.5.3"])
    end
  else
    s.add_dependency(%q<redis>, [">= 3.0.1", "~> 3.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<rake>, ["~> 0.9.2.2"])
    s.add_dependency(%q<rspec>, ["~> 2.11.0"])
    s.add_dependency(%q<timecop>, ["~> 0.5.3"])
  end
end

